channels:
  - conda-forge
  - defaults
  - andrazpolak
  - https://conda.anaconda.org/pyviz/

dependencies:
  # required
  - numpy
  - python

  # lint
  - black

  # testing
  - pytest

  # documentation
  - sphinx
  - numpydoc
  - pydata-sphinx-theme
