{% set sdata = load_setup_py_data() %}

package:
  name: atpthings
  version: {{ sdata['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py --quiet install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
  run:
    - python {{ sdata['python_requires'] }}
    {% for dep in sdata.get('install_requires',{}) %}
    - {{ dep }}
    {% endfor %}

about:
  home: {{ sdata.get('url') }}
  license: {{ sdata.get('license') }}
  summary: {{ sdata.get('description') }}
